<?php
namespace GDO\LinkUUp\Method;

use GDO\Avatar\GDT_Avatar;
use GDO\Core\GDO;
use GDO\Core\GDT_UInt;
use GDO\DB\Query;
use GDO\Table\MethodQueryCards;
use GDO\Table\MethodQueryTable;
use GDO\User\GDO_User;
use GDO\User\GDT_ProfileLink;

/**
 * Show top cuddlers in a ranking table.
 */
final class Cuddlers extends MethodQueryCards
{
    public function gdoTable(): GDO
    {
        return GDO_User::table();
    }

    public function gdoHeaders(): array
    {
        return [
            GDT_ProfileLink::make('user_name')->avatar()->username(),
            GDT_UInt::make('cuddles'),
        ];
    }

    public function gdoQuery(): Query
    {
        return parent::gdoQuery(); // TODO: Change the autogenerated stub
    }
}