root@vps29588:~# cat /etc/apache2/sites-enabled/010-linkuup.conf

<VirtualHost *:80>
        RewriteEngine On
        ServerName linkuup.de
        RewriteCond %{REQUEST_URI} "!/.well-known/acme-challenge/"
        RewriteRule ^/*(.*)$ https://%{HTTP_HOST}/$1 [NE,L,R=301]
        DocumentRoot /home/linkuup/www/linkuup-home
        <Directory "/home/linkuup/www/linkuup-home">
                Options +Indexes +FollowSymLinks -MultiViews
                AllowOverride All
                Require all granted
        </Directory>
</VirtualHost>

<VirtualHost *:443>
        ServerName linkuup.de
        DocumentRoot /home/linkuup/www/linkuup-home
        <Directory "/home/linkuup/www/linkuup-home">
                Options +Indexes +FollowSymLinks -MultiViews
                AllowOverride All
                Require all granted
        </Directory>


        Alias /backend /home/linkuup/www/gdo6/
       <Directory "/home/linkuup/www/gdo6">
                Options +Indexes +FollowSymLinks -MultiViews
                AllowOverride All
                Require all granted
        </Directory>

        SSLEngine on
        SSLProtocol all -SSLv2
        SSLCipherSuite HIGH:!aNULL:!MD5
        SSLCertificateFile /root/.acme.sh/linkuup.de/fullchain.cer
        SSLCertificateKeyFile  //root/.acme.sh/linkuup.de/linkuup.de.key

        AssignUserID linkuup linkuup
        ErrorLog /home/linkuup/www/apache.error.log
        CustomLog /home/linkuup/www/apache.access.log combined
</VirtualHost>

<VirtualHost *:80>
        RewriteEngine On
        ServerName app.linkuup.de
        RewriteCond %{REQUEST_URI} "!/.well-known/acme-challenge/"
        RewriteRule ^/*(.*)$ https://%{HTTP_HOST}/$1 [NE,L,R=301]
        DocumentRoot /home/linkuup/www/lupapp
        <Directory "/home/linkuup/www/lupapp">
                Options +Indexes +FollowSymLinks -MultiViews
                AllowOverride All
                Require all granted
        </Directory>
        AssignUserID linkuup linkuup
        ErrorLog /home/linkuup/www/app.error.log
        CustomLog /home/linkuup/www/app.access.log combined
</VirtualHost>

<VirtualHost *:443>
        ServerName app.linkuup.de
        DocumentRoot /home/linkuup/www/lupapp
        <Directory "/home/linkuup/www/lupapp">
                Options +Indexes +FollowSymLinks -MultiViews
                AllowOverride All
                Require all granted
        </Directory>

        SSLEngine on
        SSLProtocol all -SSLv2
        SSLCipherSuite HIGH:!aNULL:!MD5
        SSLCertificateFile /root/.acme.sh/app.linkuup.de/fullchain.cer
        SSLCertificateKeyFile  //root/.acme.sh/app.linkuup.de/app.linkuup.de.key

        AssignUserID linkuup linkuup
        ErrorLog /home/linkuup/www/app.error.log
        CustomLog /home/linkuup/www/app.access.log combined
</VirtualHost>


<VirtualHost *:443>
        ServerName pma.linkuup.de
        DocumentRoot /home/linkuup/www/pma
        <Directory "/home/linkuup/www/pma">
                Options +Indexes +FollowSymLinks -MultiViews
                AllowOverride All
                Require all granted
        </Directory>

        SSLEngine on
        SSLProtocol all -SSLv2
        SSLCipherSuite HIGH:!aNULL:!MD5
        SSLCertificateFile /root/.acme.sh/linkuup.de/fullchain.cer
        SSLCertificateKeyFile  //root/.acme.sh/linkuup.de/linkuup.de.key

        AssignUserID linkuup linkuup
        ErrorLog /home/linkuup/www/pma.error.log
        CustomLog /home/linkuup/www/pma.access.log combined

</VirtualHost>

